name: weatherapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  sliding_up_panel: ^1.0.2
  geolocator: ^6.1.4
  http: ^0.12.2
  intl: ^0.16.1
  flutter_google_places: ^0.2.6
  geocoder: ^0.2.1
  pull_to_refresh: ^1.6.3
  flutter_svg: ^0.19.1
  shared_preferences: ^0.5.12+4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/icons/
  - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
